// File generated by CyberShield Firebase Configuration
// Live Firebase project: cybershield-5494d

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your CyberShield Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw-PexQz2-aMSagLiINrjf2wpoyzxWVVw',
    appId: '1:915022166169:web:8756fec8a6f2796e772008',
    messagingSenderId: '915022166169',
    projectId: 'cybershield-5494d',
    authDomain: 'cybershield-5494d.firebaseapp.com',
    storageBucket: 'cybershield-5494d.firebasestorage.app',
    measurementId: 'G-2PE8B7882F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw-PexQz2-aMSagLiINrjf2wpoyzxWVVw',
    appId: '1:915022166169:android:8756fec8a6f2796e772008',
    messagingSenderId: '915022166169',
    projectId: 'cybershield-5494d',
    storageBucket: 'cybershield-5494d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-PexQz2-aMSagLiINrjf2wpoyzxWVVw',
    appId: '1:915022166169:ios:8756fec8a6f2796e772008',
    messagingSenderId: '915022166169',
    projectId: 'cybershield-5494d',
    storageBucket: 'cybershield-5494d.firebasestorage.app',
    iosBundleId: 'com.cybershield.cybershieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-PexQz2-aMSagLiINrjf2wpoyzxWVVw',
    appId: '1:915022166169:ios:8756fec8a6f2796e772008',
    messagingSenderId: '915022166169',
    projectId: 'cybershield-5494d',
    storageBucket: 'cybershield-5494d.firebasestorage.app',
    iosBundleId: 'com.cybershield.cybershieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw-PexQz2-aMSagLiINrjf2wpoyzxWVVw',
    appId: '1:915022166169:web:8756fec8a6f2796e772008',
    messagingSenderId: '915022166169',
    projectId: 'cybershield-5494d',
    authDomain: 'cybershield-5494d.firebaseapp.com',
    storageBucket: 'cybershield-5494d.firebasestorage.app',
  );
}
