// File generated by FlutterFire CLI / CyberShield Firebase Configuration
// Provides multi-platform FirebaseOptions for Android, Web, iOS, macOS, Windows

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DemoWebApiKeyCyberShield2026',
    appId: '1:102938475612:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '102938475612',
    projectId: 'cybershield-app-sec',
    authDomain: 'cybershield-app-sec.firebaseapp.com',
    storageBucket: 'cybershield-app-sec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_DemoAndroidApiKeyCyberShield2026',
    appId: '1:102938475612:android:9876543210abcdef012345',
    messagingSenderId: '102938475612',
    projectId: 'cybershield-app-sec',
    storageBucket: 'cybershield-app-sec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_DemoIosApiKeyCyberShield2026',
    appId: '1:102938475612:ios:abcdef1234567890abcdef',
    messagingSenderId: '102938475612',
    projectId: 'cybershield-app-sec',
    storageBucket: 'cybershield-app-sec.appspot.com',
    iosBundleId: 'com.cybershield.cybershieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_DemoIosApiKeyCyberShield2026',
    appId: '1:102938475612:ios:abcdef1234567890abcdef',
    messagingSenderId: '102938475612',
    projectId: 'cybershield-app-sec',
    storageBucket: 'cybershield-app-sec.appspot.com',
    iosBundleId: 'com.cybershield.cybershieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_DemoWindowsApiKeyCyberShield2026',
    appId: '1:102938475612:web:windowsclient0123456789',
    messagingSenderId: '102938475612',
    projectId: 'cybershield-app-sec',
    authDomain: 'cybershield-app-sec.firebaseapp.com',
    storageBucket: 'cybershield-app-sec.appspot.com',
  );
}
